### ISSUE TITLE
Gulp causes problems on Mac

### ISSUE THREAD

**Issue by apawlik** [stencila/website#1]
Local build and run seems to be OK on the Mac (High Sierra 10.13.3) but then none of the browsers can access the server (localhost:8080). Possible solution https://stackoverflow.com/questions/32171725/chrome-cant-open-localhost3000-with-gulp-browsersync
Once I get this to work, I will post instructions.

So far what seems to work is installing https://browsersync.io/ and viewing website through it.

**Comment by nokome** [comment]
Any update on this? It seems like it may be related to local network config rather than the Gulp config in this repo (?). Shall we close this?

**Comment by apawlik** [comment]
Yes, looks like it was something local. May be useful to point people to open `127.0.0.1:port_number` rather than `localhost:port_number` As this has solved the problem for me.
