### ISSUE TITLE
Port forum posts to blog

### ISSUE THREAD

**Issue by nokome** [stencila/website#10]
Now that the blog has been reinvigorated and integrated into the main site we should port some of the more substantive posts from the community forum. Post that would be port to the blog:

- https://community.stenci.la/t/shrinking-stencilas-docker-images-with-strace
- https://community.stenci.la/t/a-feature-list-for-stencila-sheets
- https://community.stenci.la/t/roadtrip-roundup-what-we-learned-from-5-weeks-on-the-road
- https://community.stenci.la/t/toads-in-vancouver-using-stencila-to-teach-sql-and-r-at-ubc

It should be easy to port each post: copy the source Markdown and save copies of images. Let's use the original date in the blog.

**Comment by apawlik** [comment]
Started porting in PR #18 should be done soon. Then ready to merge
Suggest porting few more forum posts as blog is featured on the website and so will see more attention.

**Comment by apawlik** [comment]
I will port also
https://community.stenci.la/t/stencila-in-the-big-apple/106
https://community.stenci.la/t/stencila-at-the-university-of-oregon/107
https://community.stenci.la/t/stencila-in-portland-oregon/112
https://community.stenci.la/t/stencila-at-uc-berkeley/113
https://community.stenci.la/t/stencila-at-ucla/115
https://community.stenci.la/t/stencila-in-santa-barbara-california/116

**Comment by nokome** [comment]
Completed. Closing
