### ISSUE TITLE
Blog requires RSS feed

### ISSUE THREAD

**Issue by gvwilson** [stencila/website#100]
There should be an RSS feed for the blog so that people can subscribe to Stencila news.

**Comment by alex-ketch** [comment]
Now that we've moved the build tooling to Hugo, it generates an RSS feed for us. The link (https://stenci.la/blog/index.xml) can be in the footer under the RSS icon.

![Screenshot 2020-08-25 at 09 44 59@2x](https://user-images.githubusercontent.com/1646307/91182175-d4b11480-e6b7-11ea-81bc-d29e2796981e.png)
