### ISSUE TITLE
https://stenci.la/ generates certificate error in browsers

### ISSUE THREAD

**Issue by nokome** [stencila/website#12]
As reported by @kayakr over in https://github.com/stencila/stencila/issues/649

Having moved to using Githup Pages for hosting http://stenci.la, HTTPS no longer works because Github Pages does not (quite) yet support HTTPS on custom domains. There are workarounds but it seems that Github is very close to enabling HTTPS support for custom domains: https://github.com/isaacs/github/issues/156#issuecomment-382376643

**Comment by nokome** [comment]
I asked Github support if they could switch us over to HTTPS. They responded:

>As you've discovered, some GitHub Pages sites have been issued SSL certificates from Let's Encrypt, enabling HTTPS for your custom domain. This isn't officially supported yet and it's not possible for you to enable and enforce it on your other sites at this time.

>We know how important secure browsing is for our users, but we don't yet have anything official to announce at this time. If and when this feature is officially released, we will announce it on our blog: https://github.com/blog

So, it we should probably find a workaround (e.g. a reverse proxy), rather than wait around for them to sort it out.

**Comment by kayakr** [comment]
@nokome have you seen https://blog.github.com/2018-05-01-github-pages-custom-domains-https/ ?

**Comment by nokome** [comment]
Hah, that's funny! Two days ago it was "if and when this feature is officially released".

Thanks for the heads up, appreciated. Will configure it later today.

**Comment by nokome** [comment]
Done.

**Comment by kayakr** [comment]
Timing was indeed funny. Thanks nokome.

**Comment by nuest** [comment]
@nokome Not really worth a new issue, but still: What about enbling redirect from http://stenci.la/ to https://stenci.la/ ? It's just a checkbox in the GitHub settings:

![image](https://user-images.githubusercontent.com/1325054/43128847-42ce5dda-8f33-11e8-859f-37f58e637614.png)

![image](https://user-images.githubusercontent.com/1325054/43128826-37b6a0a6-8f33-11e8-86a3-8ed1064c831b.png)

**Comment by nokome** [comment]
@nuest : thanks for pointing this out, done.
