### ISSUE TITLE
Integrate/link to stencila/slides repo?

### ISSUE THREAD

**Issue by nokome** [stencila/website#16]
We have a repository for presentation slides. There is some useful material in them (although they can be repetitive :man_shrugging:). Some options for making them more discover-able from the main website:

1. Create a blog post whenever we do a presentation and link to the slides from the presentation from there (we could do some back dated blog posts for some of the previous presentations)

2. Have a link to the slides repo and https://stencila.github.io/slides/ in a 'resources' or 'community' section.

3. Don't have a separate slides repo, instead make slides a part of the main website repo.

These are not mutually exclusive options. My preference is doing 1+2. I don't think 3 is necessary. Thoughts @apawlik ?

**Comment by apawlik** [comment]
I agree on 1&2 as resources link.  3 I think may be not needed and allows for adding external material (ie people contributing) without us worrying much something gets broken on main website report. Also makes it easy for people to browse through. 

Happy to take this one

**Comment by nokome** [comment]
OK, thanks. Related is #10 - essentially, this would expand the number of back dated posts we port from the forum (which have links to slides in them).

**Comment by apawlik** [comment]
Sure!  Yes,
