### ISSUE TITLE
Website feedback

### ISSUE THREAD

**Issue by michael** [stencila/website#23]
I ❤️ the community page. Very appealing with the photos and the two column image + text blocks. I think we should do a similar thing on the front page, introducing some of the core features. I can work on that and do some sketches?

Some other points:

- I still find the navigation confusing and not so effective
   - e.g. under the very prominent items "Use", "Learn" and "Contribute" there's rather boring text-ish pages hiding behind
   - I'd rather move the primary information out and put it into the startpage and community pages and then put links to further information (e.g. download stencila button on the mainpage, with a link to the complete install instructions
   - Additionally we can use the footer to allow quick navigation
- I think the blog would look much better in a one column style, it's now quite hard to see the order of the posts.
- Contribute: This looks a bit redundant with the community page to me (which is much nicer)
   - would you consider merging these two sections and have only one menu item as an entry point?
   - the call to action for contributing appears too formal to me (e.g. the list of modules to contribute to or the contribution guidelines). I'd instead write a short paragraph describing how to start contributing.  E.g. Go to github, find the sub-project (with a link to documentation where the architecture and modules are described), contact us if you need any help. The formal contribution guidelines we can have in a CONTRIBUTE.md in the repos instead of the website, to keep things slim and welcoming.

**Comment by michael** [comment]
Here's some ideas for the front page:

[Stencila-Frontpage.pdf](https://github.com/stencila/website/files/1980701/Stencila-Frontpage.pdf)

**Comment by michael** [comment]
Text from the sketches:

## A word processor designed for scientific content 

Create interactive, fully reproducible documents using a familiar visual authoring interface. Use code cells to produce figures based on data. Add an abstract and a bibliography to your article and cite figures and references, without having to worry about citation formatting.

## Spreadsheets for scientific needs 

Add data to your publication using the Stencila Sheets interface. Use formulas to do calculations, create figures next to the data and reference them in the manuscript. Cross-document updates are one of the key features of Stencila. It means that in an article you can reference data from a spreadsheet and vice versa. If you update the data in one place, all affected documents will update as well.

## Reactive code evaluation in different languages

 In Stencila code evaluates live as you type. Because the execution engine analyses the dependencies between cells, it can perform the minimal update, making computation fast and responsive. This mechanism works with all available languages (e.g. R, Python, Javascript, SQL). You can even mix languages within a document.

## Open File Format based on industry XML standards

 Stencila projects are self-contained archives of documents and assets.  We are working with authors and publishers to promote a format called Dar, which is based on existing publishing standards (such as JATS). Publishers will be able to support it as a submission format, which will make the whole publishing process much faster.

## Interoperability with existing tools and workflows 

Stencila is developed not to replace existing tools, but to complement them. We are working closely with the communities of existing open source tools to improve interoperability.  For instance we are working with the team of Jupyter on tools to turn notebooks into a journal submissions. We are also evaluating whether the Stencila editor could be used as an alternative (more visual) interface to edit Jupyter Notebooks.

## Community-driven development 

Stencila development is driven by its users. We consider every user as an integral part of the project. Using their experience and knowledge we can build a truly open set of tools meeting the needs of researchers.

**Comment by michael** [comment]
SVG file of the mockup. Please note i've really just quick-drafted things, so images should probably be replaced with higher quality ones.

[Stencila-Frontpage.svg.zip](https://github.com/stencila/website/files/1981564/Stencila-Frontpage.svg.zip)

**Comment by apawlik** [comment]
@michael This is great! Thank you SO MUCH. I had a chat with Nokome and we thought it would be a good idea to split that into separate issues which would be easier to address. I am starting on this now.

**Comment by apawlik** [comment]
Closing this one as I split it into separate issues (see above).
