### ISSUE TITLE
Generate contributors page from aggregated .all-contributorsrc files

### ISSUE THREAD

**Issue by nokome** [stencila/website#89]
PR https://github.com/stencila/website/pull/88 adds a `.all-contributorsrc` and an autogenerated all-contributors badge to the README.

I'm proposing that we go a step further and add `.all-contributorsrc` to all our repos. Then in this repo's `gulp.js` fetch an aggregate all the contributors and that "all-all-contributors" list to generate a HTML page for the website. That will be less time consuming than maintaining a HTML page by hand.

**Comment by apawlik** [comment]
Agreed and thanks for this. I will try to generate that HTML page and add to the "About" pages
